# Generated by Django 2.2.12 on 2020-09-03 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('detalle', models.TextField(blank=True)),
                ('color', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tapas.Color')),
            ],
        ),
    ]
