# Generated by Django 2.2.12 on 2020-09-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tapa',
            name='color',
        ),
        migrations.AddField(
            model_name='tapa',
            name='color',
            field=models.ManyToManyField(blank=True, to='tapas.Color'),
        ),
    ]
