# Generated by Django 2.2.12 on 2020-09-03 19:34

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tapas', '0002_auto_20200903_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='tapa',
            name='color',
        ),
        migrations.AddField(
            model_name='color',
            name='codigo',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AddField(
            model_name='tapa',
            name='imagen',
            field=models.ImageField(null=True, upload_to='tapa-files/'),
        ),
        migrations.CreateModel(
            name='TapaImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='tapa-image-files/')),
                ('link', models.CharField(blank=True, max_length=100)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_imagen', to='tapas.Color')),
                ('tapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tapa_imagen', to='tapas.Tapa')),
            ],
        ),
    ]
