# Generated by Django 2.2.12 on 2020-09-07 00:47

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapas', '0003_auto_20200903_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='codigo',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
        migrations.AlterField(
            model_name='tapa',
            name='detalle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tapa',
            name='imagen',
            field=models.ImageField(upload_to='tapa-files/'),
        ),
        migrations.AlterField(
            model_name='tapa',
            name='marca',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tapa',
            name='modelo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tapaimage',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
