# Generated by Django 2.2.12 on 2020-09-10 20:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapas', '0004_auto_20200907_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tapa',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='tapaimage',
            name='link',
        ),
        migrations.AddField(
            model_name='tapa',
            name='alto',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='tapa',
            name='ancho',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='tapa',
            name='linea',
            field=models.CharField(default='Clasica', max_length=20),
        ),
        migrations.AlterField(
            model_name='tapa',
            name='detalle',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None),
        ),
    ]
