# Generated by Django 2.2.12 on 2020-09-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapas', '0005_auto_20200910_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='tapa',
            name='detalle',
        ),
        migrations.AddField(
            model_name='tapa',
            name='caracteristicas',
            field=models.ManyToManyField(to='tapas.Caracteristica'),
        ),
    ]
