# Generated by Django 2.2.12 on 2020-09-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapas', '0006_auto_20200910_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caracteristica',
            old_name='description',
            new_name='caracteristica',
        ),
        migrations.RemoveField(
            model_name='tapa',
            name='caracteristicas',
        ),
        migrations.AddField(
            model_name='tapa',
            name='caracteristica',
            field=models.ManyToManyField(related_name='caracteristica_tapa', to='tapas.Caracteristica'),
        ),
    ]
