# Generated by Django 2.2.12 on 2020-09-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapas', '0007_auto_20200910_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tapa',
            name='alto',
            field=models.FloatField(default=30),
        ),
        migrations.AlterField(
            model_name='tapa',
            name='ancho',
            field=models.FloatField(default=30),
        ),
    ]
