# Generated by Django 2.2.12 on 2022-11-10 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tapas', '0008_auto_20200916_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea', models.CharField(default='Loza', max_length=20)),
                ('clasica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tapa_clasica', to='tapas.Tapa')),
                ('madera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tapa_madera', to='tapas.Tapa')),
                ('moderna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tapa_moderna', to='tapas.Tapa')),
            ],
        ),
    ]
