# Generated by Django 2.2.12 on 2022-11-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapas', '0009_loza'),
    ]

    operations = [
        migrations.AddField(
            model_name='loza',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='tapa-files/'),
        ),
    ]
