# Generated by Django 2.2.12 on 2022-11-11 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tapas', '0010_loza_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loza',
            name='clasica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tapa_clasica', to='tapas.Tapa'),
        ),
        migrations.AlterField(
            model_name='loza',
            name='madera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tapa_madera', to='tapas.Tapa'),
        ),
        migrations.AlterField(
            model_name='loza',
            name='moderna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tapa_moderna', to='tapas.Tapa'),
        ),
    ]
