# Generated by Django 2.2.12 on 2022-11-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapas', '0011_auto_20221111_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='tapa',
            name='comprar',
            field=models.BooleanField(default=False),
        ),
    ]
