# Generated by Django 2.2.12 on 2022-11-23 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tapas', '0012_tapa_comprar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loza',
            name='madera',
        ),
        migrations.AddField(
            model_name='loza',
            name='madera_metalico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tapa_madera_metalico', to='tapas.Tapa'),
        ),
        migrations.AddField(
            model_name='loza',
            name='madera_plastico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tapa_madera_plastico', to='tapas.Tapa'),
        ),
    ]
