# Generated by Django 2.2.12 on 2022-12-05 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tapas', '0013_auto_20221123_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tapa',
            name='imagen',
        ),
    ]
