# Generated by Django 2.2.12 on 2022-12-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapas', '0014_remove_tapa_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Texto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('texto', models.CharField(max_length=200)),
            ],
        ),
    ]
